# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
# "requirements.txt" = "selected"
# "run.sh" = "selected"
"src\\bookmark_parser.py" = "selected"
"src\\bookmark_writer.py" = "selected"
"src\\directory_scanner.py" = "selected"
"src\\main.py" = "selected"
# 