# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
"bookmark.html" = "selected"
"bookmark_script.py" = "selected"
"requirements.txt" = "selected"
"run.sh" = "selected"
# 